version: '3'

services:
  app:
    build: ./flask-api
    container_name: flask-api
    expose:
      - "5000:5000"
    restart: always
    depends_on:
      - db

  db:
    image: mysql:5.7.31
    container_name: ${MYSQL_HOST}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/dump:/docker-entrypoint-initdb.d"
      - "./etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf"
    expose:
      - "3306"
    restart: always